spring.application.name=EmployeeCRUD

#db configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Employee_CRUD
spring.datasource.username=root
spring.datasource.password=Divya
spring.jpa.hibernate.ddl-auto=update


#optional
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true
